version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.5.0
    steps:
      - checkout
      - run:
          name: Build & test
          command: |
            yarn
            yarn run build
            yarn run test
      - run:
          name: Trigger integration tests
          command: curl -X POST "https://circleci.com/api/v1.1/project/github/anishkny/realworld-e2e-test?circle-token=$CIRCLE_CI_TOKEN"
